config/routes.rb
Rails.application.routes.draw do

  resources :bookings
  devise_for :users
  resources :sections
  resources :courses

   root 'courses#index'

end

app/models/booking.rb
class Booking < ActiveRecord::Base

	validates_presence_of :time, :user_id, :course_id

	belongs_to :course
	belongs_to :user

	validate :check_time, :check_slot, on: :create

	def check_time
		hour = self.time.strftime('%H').to_i
		minitue = self.time.strftime('%M').to_i
		if (hour != 7 || minitue != 0) && (hour != 9 || minitue != 0) && (hour != 19 || minitue != 0) && (hour != 21 || minitue != 0)
			self.errors.add(:base, "Sorry, You can book course in these slots : 7 am, 7 pm, 9 am, 9 pm.") 
		end		
	end

	def check_slot
		current_user_bookings = Booking.where(user_id: self.user_id)
		current_user_bookings.each do |booking|
			if booking.time.strftime('%H').to_i == self.time.strftime('%H').to_i
				self.errors.add(:base, "Sorry, You have already booked a course in this slot.")
			end
		end
	end

end

app/models/course.rb
class Course < ActiveRecord::Base
	validates_presence_of :name, :section_id

	has_many :sections
	has_many :bookings

end

app/models/section.rb
class Section < ActiveRecord::Base

	validates_presence_of :header, :description


	belongs_to :course

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id
    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:time, :course_id, :user_id)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
    @booking = Booking.new
    @course = Course.new
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :section_id)
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:header, :description, :string)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.number_field :course_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>
<div class = "col-md-4">
<div class = "page-header"><h2><span class="glyphicon glyphicon-th"></span>Book Course</h2></div>
  <%= form_for(@booking) do |f| %>
    <% if @booking.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>
        <ul>
        <% @booking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class= "form-group">
      <%= f.label :course_id %> : 
      <%= f.collection_select :course_id, Course.all, :id, :name,{ prompt: "Select Course" },{class: "form-control"} %>
    </div>
    <br>
    <div class= "form-group">
      <%= f.label :time %> :(Slots: 7am, 7pm, 9am, 9pm) <br>
      <%= f.time_select :time ,{class: "form-control"}%>
    </div>
    <br>
    <div><%= f.submit "BOOK", class: "btn btn-primary" %> - <%= link_to 'BACK', bookings_path, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/bookings/index.html.erb
<div class="col-md-6">
<div class= "page-header"><h2><span class="glyphicon glyphicon-th"></span>Listing Bookings</h2></div>
<table class="table">
  <thead>
    <tr>
      <th>Time</th>
      <th>Course</th>
      <th>User</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.time %></td>
        <td><%= booking.course.name %></td>
        <td><%= booking.user.email %></td>
        <td><%= link_to edit_booking_path(booking) do %>
                <i class = "glyphicon glyphicon-pencil"></i>
              <% end %>
          
            <%= link_to booking, method: :delete, data: { confirm: 'Are you sure?' } do  %>
                <i class = "glyphicon glyphicon-trash"></i>
              <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <% end %>

<%= link_to 'Back', courses_path %>

app/views/bookings/show.html.erb
<p>
  <strong>Time:</strong>
  <%= @booking.time%>
</p>

<p>
  <strong>Course:</strong>
  <%= @booking.course.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @booking.user.email %>
</p>


<%= link_to 'EDIT', edit_booking_path(@booking), class:"btn btn-primary" %> - <%= link_to 'BACK', bookings_path, class:"btn btn-primary" %>

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :section_id %><br>
    <%= f.collection_select :section_id, Section.all, :id, :header %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<div class = "col-md-4">
  <div class= "page-header">
    <h2><span class="glyphicon glyphicon-th"></span>Edit Course</h2>
  </div>
    <%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class= "form-group">
    <%= f.label :name %> : 
    <%= f.text_field :name ,placeholder: "Enter Course Name",class: "form-control"%>
  </div><br>
  <div class= "form-group">
    <%= f.label :section_id %> :
    <%= f.collection_select :section_id, Section.all, :id, :header,{ prompt: "Select Section" },{class: "form-control"}  %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "ADD COURSE", class: "btn btn-primary" %> - 
	<%= link_to 'BACK', courses_path, class: "btn btn-primary" %>
  </div>
<% end %>

</div>

app/views/courses/index.html.erb
<div class ="col-md-4">
  <div class="page-header">
      <h2><span class="glyphicon glyphicon-th"></span>Listing Courses</h2>
    </div>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Section</th>
        <th>Action</th>
      </tr>
    </thead>

    <tbody>
      <% @courses.each do |course| %>
        <tr>
          <td><%= course.name %></td>
          <td><%= Section.find_by(id: course.section_id).header %></td>
          <td><%= link_to edit_course_path(course) do %>
                <i class = "glyphicon glyphicon-pencil"></i>
              <% end %>
          
            <%= link_to  course, method: :delete, data: { confirm: 'Are you sure?' } do  %>
                <i class = "glyphicon glyphicon-trash"></i>
              <% end %>
          </td>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>
  <div class ="col-md-4">
  <%if user_signed_in?%>
  <div class = "page-header"><h2><span class="glyphicon glyphicon-th"></span>Book Course</h2></div>
  <%= form_for(@booking) do |f| %>
    <% if @booking.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>
        <ul>
        <% @booking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class= "form-group">
      <%= f.label :course_id %> : 
      <%= f.collection_select :course_id, Course.all, :id, :name,{ prompt: "Select Course" },{class: "form-control"} %>
    </div>
    <br>
    <div class= "form-group">
      <%= f.label :time %> :(Slots: 7am, 7pm, 9am, 9pm) <br>
      <%= f.time_select :time ,{class: "form-control"}%>
    </div>
    <br>
    <div>
      <%= f.submit "BOOK", class: "btn btn-primary" %>
    </div>
  <% end %>

  <% end %>
</div>

<div class = "col-md-4">
  <div class= "page-header">
    <h2><span class="glyphicon glyphicon-th"></span>Add Course</h2>
  </div>
    <%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class= "form-group">
    <%= f.label :name %> : 
    <%= f.text_field :name ,placeholder: "Enter Course Name",class: "form-control"%>
  </div><br>
  <div class= "form-group">
    <%= f.label :section_id %> :
    <%= f.collection_select :section_id, Section.all, :id, :header,{ prompt: "Select Section" },{class: "form-control"}  %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "ADD COURSE", class: "btn btn-primary" %>
  </div>
<% end %>

</div>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Section:</strong>
  <%= @course.section_id %>
</p>

<%= link_to 'EDIT', edit_course_path(@course), class:"btn btn-primary"%> - <%= link_to 'BACK', courses_path, class:"btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Course Details</title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<div class = "container">
	<nav class="navbar navbar-inverse">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <a class="navbar-brand" href="#">Course Booking System</a>
	    </div>
	    <ul class="nav navbar-nav">
		      	<li class="active"><%= link_to "Course List", courses_path%> </li>
	   			<li><%= link_to "Booking List", bookings_path %></li>	
	    </ul>
	    <% if user_signed_in? %>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></li>
		   	</ul>
		   	<% end %>
	    <% if !user_signed_in?%>
	    	<ul class="nav navbar-nav navbar-right">
	      		<li><a href="/users/sign_in">Sign In<span class="glyphicon glyphicon-log-in"></span></a></li>
	      		<li><a href="/users/sign_up">Sign Up<span class="glyphicon glyphicon-log-in"></span></a></li>
	   		</ul>
	   	<% end %>
	  </div>
	</nav>

<marquee direction = "right" width="50%" style="color:red">Please Register to Book Course </marquee ><marquee direction = "left"  width="50%" style="color:green">Book the Course in These Slots : 7am, 7pm, 9am, 9pm</marquee>

	<% if notice %>
  <div class = "alert alert-success">
    <%= notice%>
  </div>
<%end%>
<% if alert %>
  <div class = "alert alert-warning">
    <%= alert %>
  </div>
<% end %>
	<%= yield %>
</div>
</body>
</html>

app/views/sections/_form.html.erb
<%= form_for(@section) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :header %><br>
    <%= f.text_field :header %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form' %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.erb
<h1>Listing Sections</h1>

<table>
  <thead>
    <tr>
      <th>Header</th>
      <th>Description</th>
      <th>String</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.header %></td>
        <td><%= section.description %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_section_path %>

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form' %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<p>
  <strong>Header:</strong>
  <%= @section.header %>
</p>

<p>
  <strong>Description:</strong>
  <%= @section.description %>
</p>


<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>